"""add scoring fields to applications

Revision ID: fc5370f99141
Revises: f6be731ffb98
Create Date: 2026-10-06 15:27:36.380682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc5370f99141'
down_revision: Union[str, Sequence[str], None] = 'f6be731ffb98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('applications', sa.Column('children', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('family_members', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('owns_car', sa.Boolean(), nullable=True))
    op.add_column('applications', sa.Column('owns_home', sa.Boolean(), nullable=True))
    op.add_column('applications', sa.Column('education', sa.String(length=30), nullable=True))
    op.add_column('applications', sa.Column('family_status', sa.String(length=30), nullable=True))
    op.add_column('applications', sa.Column('housing_type', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'housing_type')
    op.drop_column('applications', 'family_status')
    op.drop_column('applications', 'education')
    op.drop_column('applications', 'owns_home')
    op.drop_column('applications', 'owns_car')
    op.drop_column('applications', 'family_members')
    op.drop_column('applications', 'children')
    op.drop_column('applications', 'date_of_birth')
    # ### end Alembic commands ###
